# Configuration for weekly-digest - https://github.com/apps/weekly-digest
# Added by: Dave Brace @orville-wright on: 16 June 2024
#
publishDay: sun
canPublishIssues: true
canPublishPullRequests: true
canPublishContributors: true
canPublishStargazers: true
canPublishCommits: true
